# Copyright 2004-2020 L2J Server
# L2J Server is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# L2J Server is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. 

version: '0.1'

services:
  mariadb:
    container_name: lineternity-server-mariadb
    image: yobasystems/alpine-mariadb:10.4.13
    volumes:
      - /var/lib/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
  lineternity-server:
    container_name: lineternity-server-docker
    image: lineternity/lineternity-server-docker:latest
    restart: always
    environment:
      IP_ADDRESS: ${GAMESERVER_ADDRESS}
      RATE_XP: "1"
      RATE_SP: "1"
      ADMIN_RIGHTS: "True"
      HELLBOUND_ACCESS: "True"
      TVT_ENABLED: "True"
      FORCE_GEODATA: "False"
      COORD_SYNC: "-1"
      BUFFER_SERVICE: "True"
      CUSTOM_NPC_DATA: "True"
      SAVE_GM_SPAWN_ON_CUSTOM: "True"
      CUSTOM_SPAWNLIST_TABLE: "True"
      CUSTOM_TELEPORT_TABLE: "True"
      CUSTOM_NPC_BUFFER_TABLES: "True"
      CUSTOM_SKILLS_LOAD: "True"
      CUSTOM_ITEMS_LOAD: "True"
      CUSTOM_MULTISELL_LOAD: "True"
      CUSTOM_BUYLIST_LOAD: "True"
      ALT_WEIGHT_LIMIT: "100"
    depends_on:
      - mariadb
    ports:
      - "7777:7777"
      - "2106:2106"
